# Generated by Django 3.2.16 on 2022-11-03 06:40

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Thiruvanathapuram', 'tvm'), ('Ernakulam', 'ekm'), ('Calicut', 'clt'), ('Thrissur', 'thr'), ('Kottayam', 'ktym')], max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('link', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'verbose_name': 'district',
                'verbose_name_plural': 'districts',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=199, unique=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank_app.branches')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'student',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(default=models.CharField(max_length=100, unique=True), max_length=100)),
                ('dob', models.DateField(blank=True)),
                ('age', models.IntegerField(blank=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Transgender', 'Transgender')], max_length=30)),
                ('phonenumber', models.IntegerField(blank=True)),
                ('mailid', models.EmailField(blank=True, max_length=300)),
                ('address', models.TextField(blank=True, max_length=200)),
                ('account', models.CharField(choices=[('Savings Account', 'SA'), ('Current Account', 'CA')], max_length=200)),
                ('material', multiselectfield.db.fields.MultiSelectField(choices=[('Credit Card', 'Credit Card'), ('Debit Card', 'Debit Card'), ('Pass Book', 'Pass Book')], max_length=32)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank_app.city')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank_app.branches')),
            ],
            options={
                'verbose_name': 'task',
                'verbose_name_plural': 'tasks',
                'ordering': ['name'],
            },
        ),
    ]
