# Generated by Django 3.2.16 on 2022-11-03 06:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='slug',
            field=models.SlugField(default=uuid.uuid1, max_length=100),
        ),
    ]
